name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # Use Node.js 16

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Replace with your build command

    - name: Deploy to Server
      run: |
        # Replace this with your deployment script or commands
        # After deploying, start your Node.js server
        node server.js  # Replace with the correct entry point for your Express.js app
