name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Deploy to Server
      run: |
        # Start the server in the background
        node server.js &

        # Define the timeout duration (in seconds)
        timeout=30
        for ((i=0; i<$timeout; i++)); do
          # Check if the server is responding
          if [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:3000)" == "200" ]]; then
            break
          fi
          sleep 5
        done

        # Run your tests or any other actions that depend on the server
        # For example: npm test

        # Stop the server gracefully
        pkill -f "node server.js"
    # This job will have a default timeout of 6 hours
