name: Deploy, Install Browsers, Run Playwright Tests, and Stop Server

on:
  push:
    branches:
      - main

jobs:
  deploy_run_and_stop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Deploy Application
        run: node server.js &

      - name: Wait for Server
        run: |
          timeout=30
          for ((i=0; i<$timeout; i++)); do
            if [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:3000)" == "200" ]]; then
              break
            fi
            sleep 5
          done

      - name: Install Playwright Browsers
        run: npx playwright install
        
      - name: Install Jest
        run: npm install jest --save-dev

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Stop Server
        run: pkill -f "node server.js"
